# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build super_cartographers
on: 
  workflow_dispatch:
  push:
    paths:
    - 'datapacks/super_cartographers/**/*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: install zip
        uses:  montudor/action-zip@v1
      - name: zip datapack
        working-directory: datapacks/super_cartographers
        run: zip -qq -r super_cartographers.${{ github.sha }}.zip pack.mcmeta data
      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: datapacks/super_cartographers/super_cartographers.${{ github.sha }}.zip
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: super-cartographers
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files-primary: datapacks/super_cartographers/super_cartographers.${{ github.sha }}.zip
          loaders: datapack
          dependencies: sjvt | depends | *
