# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build super_cartographers
on: 
  push:
    paths:
    - 'datapacks/super_cartographers/**/*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: datapacks/super_cartographers
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: zip datapack
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r super_cartographers.${{ github.sha }}.zip *

      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: super_cartographers.${{ github.sha }}.zip
