# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build super_cartographers
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: zip datapack
        working-directory: datapacks/super_cartographers
        run: zip -qq -r datapacks/super_cartographers.${{ github.sha }}.zip *

      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: datapacks/super_cartographers.${{ github.sha }}.zip
